### ISSUE TITLE
except Exception should be also avoided

### ISSUE THREAD

**Issue by hvelarde** [elijahandrews/flake8-blind-except#4]
almost all Python exceptions [inherit from Exception](https://docs.python.org/2/library/exceptions.html#exception-hierarchy).

so, from QA point of view, using `except Exception:` is almost as bad as using `except:`.

**Comment by jayvdb** [comment]
This should be a different error code so it can be excluded.

**Comment by elijahandrews** [comment]
Sorry I'm just getting around to looking at this now. I didn't realize that other people were using this! I'll probably make this a different error code as @jayvdb suggested, likely B902.

I know one difference between `except Exception:` and `except:` is that `except:` catches system interrupt calls. The reason I was annoyed with `except:` was because I was finding code that would catch `SIGINT` (from Control-C) in places where it really shouldn't have. I can see why you'd also want to disallow `except Exception:`.

**Comment by danpalmer** [comment]
Ping on this, would be a nice feature :)

**Comment by elijahandrews** [comment]
Hey @danpalmer, thanks for the ping! I'm not working on much Python these days, so realistically I won't be getting around to this anytime soon. PRs are welcome though!
